[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk

# This flag enables printf() over USB and is required for stdio_usb_connected
build_flags = -DPICO_STDIO_USB=1

build_src_flags = -O0
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200